security:
    password_hashers:
        App\Entity\Membre:
            algorithm: bcrypt

    providers:
        membres_provider:
            entity:
                class: App\Entity\Membre
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: membres_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: home

    access_control:
       # - { path: ^/login$, roles: PUBLIC_ACCESS }
       # - { path: ^/register$, roles: PUBLIC_ACCESS }
       # - { path: ^/, roles: ROLE_USER }

# Configurations spécifiques à l'environnement de test
when@test:
    security:
        password_hashers:
            App\Entity\Membre:
                algorithm: bcrypt
                cost: 4
