when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

home: ## nom de la route
    path: / ## url 
    controller: App\Controller\HomeController::index ## la méthode à appeler

    # composer.json autoload App\ => src/ 

search: 
    path: /search
    controller: App\Controller\SearchController::index

ajouter: 
    path: /ajouter-vehicule
    controller: App\Controller\AjouterVehiculeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::index

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::index

app_reservation:
    path: /reservation
    controller: App\Controller\ReservationController::index